Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.DependencyInjection;

namespace RecipeAssignment.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
        {
        }

        public DbSet<Recipe> Recipes { get; set; }
    }

    public class ApplicationDbContextFactory
            : IDesignTimeDbContextFactory<ApplicationDbContext> {

            public ApplicationDbContext CreateDbContext(string[] args) =>
                Program.BuildWebHost(args).Services
                    .GetRequiredService<ApplicationDbContext>();
        }
}

Models/EFRecipeRepo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;


namespace RecipeAssignment.Models
{
    public class EFRecipeRepo : IRecipeRepo
    {
        private ApplicationDbContext context;

        public EFRecipeRepo(ApplicationDbContext ctx)
        {
            context = ctx;
        }

        public new IQueryable<Recipe> Recipes => context.Recipes;
    }
}

Models/FakeRecipeRepo.cs
using System.Collections.Generic;
using System.Linq;

namespace RecipeAssignment.Models
{
    public class FakeRecipeRepo : IRecipeRepo
    {
        public IQueryable<Recipe> Recipes => new List<Recipe>
        {
            new Recipe()
            {
                RecipeName = "Bheja Fry",
                Ingredients = "Brain",
                Directions = "nohting",
                Rating = "5 Star",
                RatingReview = "Nothing to show rating "
            }
        }.AsQueryable<Recipe>();
    }
}

Models/IRecipeRepo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RecipeAssignment.Models
{
    public class IRecipeRepo
    {
        private static List<Recipe> recipes = new List<Recipe>();

        public static IEnumerable<Recipe> Recipes
        {
            get
            {
                return recipes;

            }
         }

        public static void AddRecipe(Recipe recipe)
        {
            recipes.Add(recipe);
        }
    }
}

Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace RecipeAssignment.Models
{
    public class Recipe
    {
        [Key]
        public string RecipeName { get; set; }
        public string Ingredients { get; set; }
        public string Directions { get; set; }
        public string Rating { get; set; }
        public string RatingReview { get; set; }
    }
}

Models/SeedData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;

namespace RecipeAssignment.Models
{
    public static class SeedData
    {
        public static void EnsurePopulated(IApplicationBuilder app)
        {
            ApplicationDbContext context = app.ApplicationServices
            .GetRequiredService<ApplicationDbContext>();
            context.Database.Migrate();
            if (!context.Recipes.Any())
            {
                context.Recipes.AddRange(
                new Recipe
                {
                    RecipeName = "Chocolate Chip Cookies",
                    Ingredients = "1 cup butter softened, 1 cup white sugar, 2 eggs, 2 teaspoons vanilla extract, 1 teaspoon baking soda, 2 teaspoons hot water, 1/2 teaspoon salt, 3 cups all-purpose flour, 2 cups semisweet chocolate chips ",
                    Rating = "5",
                    Directions = "1. Preheat oven to 350 degrees F (175 degrees C). , 2. Cream together the butter, white sugar, and brown sugar until smooth. Beat in the eggs one at a time, then stir in the vanilla. Dissolve baking soda in hot water. Add to batter along with salt. Stir in flour, chocolate chips, and nuts. Drop by large spoonfuls onto ungreased pans , 3. Bake for about 10 minutes in the preheated oven, or until edges are nicely browned."
                });
                context.SaveChanges();
            }
         }
    }
}

Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RecipeAssignment.Models;

namespace RecipeAssignment.Controllers
{
    public class RecipeController : Controller
    {
        /*private IRecipeRepo repository;

        public RecipeController(IRecipeRepo repo)
        {
            repository = repo;
        }*/

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ViewResult InsertPage()
        {
            return View();
        }
        [HttpPost]
        public ViewResult InsertPage(Recipe recipe)
        {
            IRecipeRepo.AddRecipe(recipe);
            return View("DataPage", IRecipeRepo.Recipes);
        }
        public ViewResult DisplayPage()
        {
            return View(IRecipeRepo.Recipes);
        }
        public ViewResult DataPage()
        {
            return View(IRecipeRepo.Recipes);
        }
        [HttpGet]
        public ViewResult UserPage()
        {
            return View();
        }
        [HttpPost]
        public ViewResult UserPage(Recipe recipe)
        {
            return View("DisplayPage", IRecipeRepo.Recipes);
        }

    }
}

Views/Recipe/DataPage.cshtml
@model System.Collections.Generic.IEnumerable<RecipeAssignment.Models.Recipe>
@{ 
    Layout = null;

}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/css/styles.css" />
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <nav class="navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Baking Recipes</a>
                </div>
                <center>
                    <a asp-action="Index">Home</a>
                    <a asp-action="InsertPage">Add Recipe</a>
                    <a asp-action="DataPage">View Recipes</a>
                </center>
            </div>
        </nav>
        <br />
        <h1>List of Recipes</h1>
        <table>
            <thead>
                <tr>
                    <th>Recipe Name</th>
                    <th>Rating</th>
                </tr>
            </thead>
            <tbody>
                @foreach (RecipeAssignment.Models.Recipe r in Model)
                {
                <tr>
                    <td><a asp-action="DisplayPage">@r.RecipeName</a></td>
                    <td>@r.Rating</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Views/Recipe/DisplayPage.cshtml
@model System.Collections.Generic.IEnumerable<RecipeAssignment.Models.Recipe>
@{
    ViewData["Title"] = "DisplayPage";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/css/styles.css" />
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <nav class="navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Baking Recipes</a>
                </div>
                <center>
                    <a asp-action="Index">Home</a>
                    <a asp-action="InsertPage">Add Recipe</a>
                    <a asp-action="DataPage">View Recipes</a>
                </center>
            </div>
        </nav>
        
        <table>
            <tr>
                <td>
                    <h2>Ingredients:</h2>
            <tbody>
                @foreach (RecipeAssignment.Models.Recipe r in Model)
                {
                    <tr>
                        <td>@r.Ingredients</td>
                    </tr>
                }
            </tbody>
            </td>
            <td>
                <h2>Directions:</h2>
            <tbody>
                @foreach (RecipeAssignment.Models.Recipe r in Model)
                {
                    <tr>
                        <td>@r.Directions</td>
                    </tr>
                }
            </tbody>
            </td>
            </tr>
            <h2>Rating:</h2>
            <tbody>
                @foreach (RecipeAssignment.Models.Recipe r in Model)
                {
                <tr>
                    <td>@r.Rating</td>
                    <td>@r.RatingReview</td>
                    <td><a asp-action="UserPage">Create Rating</a></td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

Views/Recipe/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<!DOCTYPE html>
<html>
<head>
    <!--
    <link rel="stylesheet" href="/css/styles.css" />
    <link rel="stylesheet" href="/lib/bootstrap/dist/css/bootstrap.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>-->
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css"/>
</head>
<body>
<div>

    <header class="navbar">
        <section class="navbar-section">
            <a class="navbar-brand mr-2" asp-action="Index">Home</a>\
            <a class="btn btn-link" asp-action="InsertPage">Add Recipe</a>
            <a class="btn btn-link" asp-action="DataPage">View Recipes</a>
        </section>
    </header>`
<br/>
<!--<center><img src="~/images/homeBaking.jpg" /></center>-->
<br/>
<h2>About</h2>
<br/>
Welcome to baking recipes! Here, you will be able to enter your own recipes, as well as give a rating on existing recipes. Of course, you will also be able to view
details of each listed recipe.
</div>
</body>
</html>

Views/Recipe/InsertPage.cshtml
<!--model Recipe

<div class="row orderForm">
    <form asp-controller="Recipe" asp-action="InsertPage" method="post" class="form-horizontal" role="form">
        <!-- Html.HiddenFor(x => x.Referer) 
<h3 class="col-md-offset-2">Add Recipe</h3>
<div class="form-group">
    <label asp-for="RecipeName" class="col-md-2 control-label">Recipe Name:</label>
    <div class="col-md-6">
        <input asp-for="RecipeName" class="form-control" placeholder="Enter recipe name" />
        <span asp-validation-for="RecipeName" class="text-danger"></span>
    </div>
    <label asp-for="Ingredients" class="col-md-2 control-label">Ingredients:</label>
    <div class="col-md-6">
        <input asp-for="Ingredients" class="form-control" placeholder="Enter the Ingredients" />
        <span asp-validation-for="Ingredients" class="text-danger"></span>
    </div>
    <label asp-for="Directions" class="col-md-2 control-label">Directions:</label>
    <div class="col-md-6">
        <input asp-for="Directions" class="form-control" placeholder="Enter the Directions" />
        <span asp-validation-for="Directions" class="text-danger"></span>
    </div>
</div>
<div class="form-group">
    <div class="btn-group col-md-offset-2 col-md-6">
        <input class="btn btn-default" type="submit" value="Cancel" asp-controller="Recipe" asp-action="Index" />
        <input class="btn btn-success" type="submit" value="Create" asp-controller="Recipe" asp-action="DataPage" />
    </div>
</div>
    </form>
</div>
-->
@model RecipeAssignment.Models.Recipe

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/css/styles.css" />
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <!--<meta name="viewport" content="width=device-width" />-->
    <title>Add Recipe</title>
</head>
<body>
    <div>
        <nav class="navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Baking Recipes</a>
                </div>
                <center>
                    <a asp-action="Index">Home</a>
                    <a asp-action="InsertPage">Add Recipe</a>
                    <a asp-action="DataPage">View Recipes</a>
                </center>
            </div>
        </nav>
        <br />
        <form class="p-a-1" asp-action="InsertPage" method="post">
            <p>
                <div class="form-group">
                    <label asp-for="RecipeName">Recipe Name:</label>
                    <input class="form-control" asp-for="RecipeName" />
                </div>
            </p>
            <p>
                <div class="form-group">
                    <label asp-for="Directions">Directions:</label>
                    <input class="form-control" asp-for="Directions" />
                </div>
            </p>
            <p>
                <div class="form-group">
                    <label asp-for="Ingredients">Ingredients:</label>
                    <input class="form-control" asp-for="Ingredients" />
                </div>
            </p>
            <div class="text-center">
                <button class="btn btn-primary" type="submit">Submit Recipe</button>
            </div>
        </form>
    </div>
</body>
</html>
   

Views/Recipe/UserPage.cshtml
@model RecipeAssignment.Models.Recipe
@{
    ViewData["Title"] = "UserPage";
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="/css/styles.css" />
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        <nav class="navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#">Baking Recipes</a>
                </div>
                <center>
                    <a asp-action="Index">Home</a>
                    <a asp-action="InsertPage">Add Recipe</a>
                    <a asp-action="DataPage">View Recipes</a>
                </center>
            </div>
        </nav>
        <br />
        <form class="p-a-1" asp-action="UserPage" method="post">
            <p>
                <div class="form-group">
                    <label asp-for="RatingReview">Your Thoughts on the Recipe:</label>
                    <input class="form-control" asp-for="RatingReview" />
                </div>
            </p>
            <p>
                <div class="form-group">
                    <select class="form-control" name="Rating">
                        <option value="1">1 Star</option>
                        <option value="2">2 Stars</option>
                        <option value="3">3 Stars</option>
                        <option value="4">4 Stars</option>
                        <option value="5">5 Stars</option>
                    </select>
                </div>
            </p>
            <div class="text-center">
                <button class="btn btn-primary" type="submit">Submit Rating</button>
            </div>
        </form>
    </div>
</body>
</html>

Views/Shared/AddRecipe.cshtml
@model Recipe

<div class="row orderForm">
    <form asp-controller="Recipe" asp-action="InsertPage" method="post" class="form-horizontal" role="form">
        <!-- Html.HiddenFor(x => x.Referer) -->
        <h3 class="col-md-offset-2">Add Recipe</h3>
        <div class="form-group">
            <label asp-for="RecipeName" class="col-md-2 control-label">Recipe Name:</label>
            <div class="col-md-6">
                <input asp-for="RecipeName" class="form-control" placeholder="Enter recipe name" />
                <span asp-validation-for="RecipeName" class="text-danger"></span>
            </div>
            <label asp-for="Ingredients" class="col-md-2 control-label">Ingredients:</label>
            <div class="col-md-6">
                <input asp-for="Ingredients" class="form-control" placeholder="Enter the Ingredients" />
                <span asp-validation-for="Ingredients" class="text-danger"></span>
            </div>
            <label asp-for="Directions" class="col-md-2 control-label">Directions:</label>
            <div class="col-md-6">
                <input asp-for="Directions" class="form-control" placeholder="Enter the Directions" />
                <span asp-validation-for="Directions" class="text-danger"></span>
            </div>
        </div>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <!-- Spectre css -->
    <link rel="stylesheet" href="https://unpkg.com/spectre.css/dist/spectre.min.css">
    <title>Recipes</title>
</head>
<body>
    

<div class="row m-1 p-1">
    <div id="categories" class="col-3">
    </div>
    <div class="col-9">
        @RenderBody()
    </div>
</div>
</body>
</html>